"""Executive valuation insight built only from persisted results and scenario vectors.

Every sentence is a template filled with a number computed here or persisted in
the SimulationResult; nothing is generated by a language model. Wording rules:
say "half" only when it is true, never call an unreached target impossible, and
describe associations, never causes. Text is pt-BR and uses only characters
available in the PDF base fonts.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any

import numpy as np

from app.decision.catalog import VariableSpec, describe, split_by_role
from app.decision.sensitivity import rank_drivers
from app.decision.targets import wilson_interval
from app.decision.uncertainty import assess_uncertainty

from .conditions import MIN_EFFECT, Condition, target_conditions
from .formatting import compact_money, multiplier, percent, share
from .tails import TailShift, tail_shifts

INSIGHT_TEMPLATE_VERSION = "insight-v1"
MIN_DRIVER_SHARE = 0.05
MIN_BINARY_EFFECT = 0.05
LOW_FIT = 0.6
PARAMETER_CONDITIONS = ("annual_wacc", "terminal_growth", "exit_multiple", "failure_state")
UNCERTAINTY_PT = {"LOW": "Baixa", "MODERATE": "Moderada", "HIGH": "Alta", "VERY HIGH": "Muito alta"}


@dataclass(frozen=True, slots=True)
class UncertaintyInsight:
    label: str
    label_pt: str
    reason: str
    sentence: str


@dataclass(frozen=True, slots=True)
class DriverInsight:
    name: str
    label: str
    contribution: float
    direction: str | None


@dataclass(frozen=True, slots=True)
class TailInsight:
    name: str
    label: str
    kind: str
    direction: str
    text: str


@dataclass(frozen=True, slots=True)
class ConditionInsight:
    name: str
    label: str
    unit: str | None
    kind: str
    direction: str
    hit_value: float
    miss_value: float
    cliffs_delta: float
    threshold: float | None


@dataclass(frozen=True, slots=True)
class TargetInsight:
    target: float
    probability: float
    hit_count: int
    scenario_count: int
    wilson95_low: float
    wilson95_high: float
    sample_note: str
    headline: str
    probability_sentence: str
    interpretation: str
    statements: tuple[str, ...]
    conditions: tuple[ConditionInsight, ...]
    disclaimer: str


@dataclass(frozen=True, slots=True)
class InsightReport:
    template_version: str
    headline: str
    valuation_paragraphs: tuple[str, ...]
    uncertainty: UncertaintyInsight
    key_drivers_sentence: str | None
    key_drivers: tuple[DriverInsight, ...]
    upside: tuple[TailInsight, ...]
    downside: tuple[TailInsight, ...]
    sensitivity_sentence: str | None
    risks: tuple[str, ...]
    target: TargetInsight | None
    executive_summary: tuple[str, ...]
    method_notes: tuple[str, ...]


def _integer(value: int) -> str:
    return f"{value:,}".replace(",", ".")


def _capitalize(text: str) -> str:
    return text[:1].upper() + text[1:]


def _join(items: Sequence[str]) -> str:
    return items[0] if len(items) == 1 else f"{', '.join(items[:-1])} e {items[-1]}"


def _value(spec: VariableSpec, value: float, currency: str) -> str:
    if spec.unit == "currency":
        return compact_money(value, currency)
    if spec.unit in {"ratio", "binary"}:
        return percent(value)
    if spec.unit == "multiplier":
        return multiplier(value)
    return f"{value:.2f}".replace(".", ",")


def _phrase(spec: VariableSpec, direction: str) -> str:
    return spec.higher if direction == "higher" else spec.lower


class _Context:
    def __init__(
        self,
        summary: Mapping[str, Any],
        valuations: np.ndarray,
        factors: Mapping[str, np.ndarray],
        currency: str,
    ) -> None:
        self.summary = summary
        self.values = np.asarray(valuations, dtype=np.float64)
        self.factors = factors
        self.currency = currency
        self.count = int(self.values.size)
        self.p = summary["percentiles"]

    def money(self, value: float) -> str:
        return compact_money(value, self.currency)


def _valuation_paragraphs(ctx: _Context) -> tuple[str, ...]:
    p, values, n = ctx.p, ctx.values, ctx.count
    below = float(np.mean(values < p["p50"]))
    above = float(np.mean(values > p["p50"]))
    at = 1.0 - below - above
    if at <= 1.0 / n + 1e-12:
        split = "Metade dos cenários produziu valuations abaixo desse valor e metade acima."
    else:
        split = (
            f"{share(below)} dos cenários ficaram abaixo desse valor, {share(above)} acima "
            f"e {share(at)} exatamente nesse valor."
        )
    first = (
        f"Nos {_integer(n)} cenários simulados, o valuation mediano da empresa foi de "
        f"{ctx.money(p['p50'])}. {split}"
    )
    inside = float(np.mean((values >= p["p25"]) & (values <= p["p75"])))
    concentration = (
        "faixa onde se concentra metade dos cenários simulados"
        if abs(inside - 0.5) <= 0.01
        else f"faixa que concentra {share(inside)} dos cenários simulados"
    )
    second = (
        f"O intervalo central P25–P75 ficou entre {ctx.money(p['p25'])} e "
        f"{ctx.money(p['p75'])}, {concentration}."
    )
    conservative = f"Em um cenário mais conservador (P10), o valuation foi de {ctx.money(p['p10'])}"
    if p["p10"] <= 0:
        conservative += ", ou seja, o valor para os sócios não seria positivo nesse extremo"
    third = (
        f"{conservative}. Em um cenário mais otimista (P90), o valuation alcançou "
        f"{ctx.money(p['p90'])}."
    )
    paragraphs = [first, second, third]
    failure = float(ctx.summary.get("failure_probability", 0.0))
    if failure > 0:
        paragraphs.append(
            f"Em {percent(failure)} dos cenários a empresa encerrou as operações dentro do "
            "horizonte de cinco anos."
        )
    return tuple(paragraphs)


def _uncertainty(ctx: _Context) -> UncertaintyInsight:
    stored = ctx.summary.get("uncertainty")
    if isinstance(stored, Mapping):
        data = dict(stored)
    else:
        p = ctx.p
        assessment = assess_uncertainty(
            p10=p["p10"], p25=p["p25"], p50=p["p50"], p75=p["p75"], p90=p["p90"],
            non_positive_probability=float(ctx.summary["non_positive_probability"]),
        )
        data = {
            "label": assessment.label,
            "reason": assessment.reason,
            "iqr": assessment.iqr,
            "iqr_ratio": assessment.iqr_ratio,
            "non_positive_probability": assessment.non_positive_probability,
        }
    label_pt = UNCERTAINTY_PT[data["label"]]
    if data["reason"] == "median_not_positive":
        sentence = (
            "Incerteza muito alta: o valuation mediano não é positivo, por isso a dispersão "
            "relativa não se aplica; a amplitude do intervalo P25–P75 é de "
            f"{ctx.money(data['iqr'])}."
        )
    elif data["reason"] == "material_non_positive_mass":
        sentence = (
            f"Incerteza muito alta: {percent(data['non_positive_probability'])} dos cenários "
            "resultaram em valuation igual ou inferior a zero."
        )
    else:
        sentence = (
            f"Incerteza {label_pt.lower()}: o intervalo P25–P75 representa "
            f"{percent(data['iqr_ratio'], decimals=0)} do valuation mediano."
        )
    return UncertaintyInsight(data["label"], label_pt, data["reason"], sentence)


def _ranking(ctx: _Context) -> Mapping[str, Any]:
    stored = ctx.summary.get("drivers")
    if isinstance(stored, Mapping):
        return stored
    drivers, _ = split_by_role(ctx.factors)
    ranking = rank_drivers(drivers, ctx.values)
    return {
        "r_squared": ranking.r_squared,
        "items": [
            {"name": d.name, "contribution": d.contribution, "direction": d.direction}
            for d in ranking.drivers
        ],
    }


def _key_drivers(ranking: Mapping[str, Any]) -> tuple[tuple[DriverInsight, ...], str | None]:
    material = [
        DriverInsight(
            item["name"], describe(item["name"]).label, item["contribution"], item["direction"]
        )
        for item in ranking["items"]
        if item["contribution"] is not None and item["contribution"] >= MIN_DRIVER_SHARE
    ][:3]
    if not material:
        return (), None
    labels = _join([d.label for d in material])
    shares = _join([percent(d.contribution, decimals=0) for d in material])
    if len(material) == 1:
        sentence = f"O fator que mais explicou a dispersão do valuation foi {labels}"
    else:
        count = "dois" if len(material) == 2 else "três"
        sentence = f"Os {count} fatores que mais explicaram a dispersão do valuation foram {labels}"
    respectively = "" if len(material) == 1 else ", respectivamente"
    sentence += f", com {shares} da variância explicada{respectively}."
    r_squared = ranking.get("r_squared")
    if r_squared is not None and r_squared < LOW_FIT:
        sentence += (
            f" Esses fatores explicam apenas {percent(r_squared, decimals=0)} da variação; "
            "interações e efeitos não lineares também pesam."
        )
    return tuple(material), sentence


def _tail_text(ctx: _Context, shift: TailShift) -> TailInsight:
    spec = describe(shift.name)
    phrase = _capitalize(_phrase(spec, shift.direction))
    group = "melhores" if shift.tail == "upside" else "piores"
    where = f"nos {share(shift.group_share)} {group} cenários"
    if shift.kind == "binary":
        body = f"{percent(shift.group_value)} {where}, contra {percent(shift.overall_value)}"
    else:
        body = (
            f"mediana de {_value(spec, shift.group_value, ctx.currency)} {where}, contra "
            f"{_value(spec, shift.overall_value, ctx.currency)}"
        )
    return TailInsight(
        shift.name, spec.label, shift.kind, shift.direction, f"{phrase} — {body} no conjunto."
    )


def _sensitivity(ctx: _Context) -> str | None:
    stored = ctx.summary.get("sensitivity")
    if not isinstance(stored, Mapping) or not stored.get("items"):
        return None
    top = stored["items"][0]
    if top["swing"] <= 0:
        return None
    spec = describe(top["parameter"])
    return (
        f"Premissa de maior impacto no tornado — {spec.label}: entre "
        f"{_value(spec, top['low_level'], ctx.currency)} e "
        f"{_value(spec, top['high_level'], ctx.currency)}, o valuation mediano varia de "
        f"{ctx.money(top['value_at_low'])} a {ctx.money(top['value_at_high'])}."
    )


def _condition_variables(factors: Mapping[str, np.ndarray]) -> dict[str, np.ndarray]:
    _, outcomes = split_by_role(factors)
    if not outcomes:
        return dict(factors)
    chosen = dict(outcomes)
    chosen.update({name: factors[name] for name in PARAMETER_CONDITIONS if name in factors})
    return chosen


def _material(condition: Condition) -> bool:
    limit = MIN_BINARY_EFFECT if condition.kind == "binary" else MIN_EFFECT
    return abs(condition.cliffs_delta) >= limit


def _statement(ctx: _Context, condition: Condition, base_rate: float) -> str:
    spec = describe(condition.name)
    if condition.kind == "binary":
        return (
            f"{spec.label}: {percent(condition.hit_value)} entre os cenários que atingem a "
            f"meta, contra {percent(condition.miss_value)} entre os demais."
        )
    if condition.threshold is None or condition.hit_rate_beyond_threshold is None:
        return (
            f"{spec.label}: mediana de {_value(spec, condition.hit_value, ctx.currency)} nos "
            "cenários que atingem a meta, contra "
            f"{_value(spec, condition.miss_value, ctx.currency)} nos demais."
        )
    side = "acima" if condition.direction == "higher" else "abaixo"
    coverage = condition.threshold_coverage or 0.0
    return (
        f"{spec.label} {side} de {_value(spec, condition.threshold, ctx.currency)}: "
        f"{share(coverage)} dos cenários que atingem a meta estavam {side} desse nível, e "
        f"entre todos os cenários {side} dele {percent(condition.hit_rate_beyond_threshold)} "
        f"atingem a meta (contra {percent(base_rate)} no total)."
    )


def _target(ctx: _Context, target: float) -> TargetInsight:
    result = target_conditions(_condition_variables(ctx.factors), ctx.values, target)
    n, hits = ctx.count, result.hit_count
    low, high = wilson_interval(hits, n)
    goal = ctx.money(target)
    if hits == 0:
        probability_sentence = (
            f"Nenhum dos {_integer(n)} cenários atingiu valuation de {goal} ou mais. Isso não "
            "significa que o resultado seja impossível, apenas que não ocorreu sob estas "
            f"premissas (limite superior de 95%: {percent(high)})."
        )
    else:
        probability_sentence = (
            f"A probabilidade simulada de o valuation atingir {goal} ou mais foi de "
            f"{percent(result.base_rate)} ({_integer(hits)} de {_integer(n)} cenários; "
            f"intervalo de 95% do erro Monte Carlo: {percent(low)} a {percent(high)})."
        )
    material = [c for c in result.conditions if _material(c)]
    if result.sample_note == "empty_group":
        interpretation = "Não há cenários nos dois grupos para comparar as condições da meta."
    elif material:
        phrases = [_phrase(describe(c.name), c.direction) for c in material[:2]]
        verb = "a principal diferença é" if len(phrases) == 1 else "as principais diferenças são"
        interpretation = (
            f"Nos cenários em que o valuation atinge {goal} ou mais, {verb} {_join(phrases)}."
        )
    else:
        interpretation = (
            f"Nos cenários em que o valuation atinge {goal} ou mais, nenhuma variável isolada "
            "se diferencia com clareza; o resultado depende de uma combinação de fatores."
        )
    statements = [_statement(ctx, c, result.base_rate) for c in material[:3]]
    smallest = min(result.hit_count, result.miss_count)
    if result.sample_note == "small_group":
        statements.append(
            f"Atenção: o menor grupo tem apenas {_integer(smallest)} cenários; as comparações "
            "são instáveis."
        )
    elif result.sample_note == "insufficient":
        statements.append(
            f"O menor grupo tem apenas {_integer(smallest)} cenários, poucos para estimar "
            "limiares; são mostradas somente as medianas."
        )
    conditions = tuple(
        ConditionInsight(
            c.name,
            describe(c.name).label,
            describe(c.name).unit,
            c.kind,
            c.direction,
            c.hit_value,
            c.miss_value,
            c.cliffs_delta,
            c.threshold,
        )
        for c in result.conditions
    )
    return TargetInsight(
        target,
        result.base_rate,
        hits,
        n,
        low,
        high,
        result.sample_note,
        f"Probabilidade de atingir {goal}: {percent(result.base_rate)}",
        probability_sentence,
        interpretation,
        tuple(statements),
        conditions,
        "Essas diferenças descrevem associações entre os cenários simulados, não relações "
        "de causa e efeito.",
    )


def _risks(
    ctx: _Context,
    uncertainty: UncertaintyInsight,
    downside: Sequence[TailInsight],
    sensitivity: str | None,
    r_squared: float | None,
) -> tuple[str, ...]:
    risks: list[str] = []
    failure = float(ctx.summary.get("failure_probability", 0.0))
    if failure > 0:
        risks.append(f"Encerramento das operações em {percent(failure)} dos cenários.")
    non_positive = float(ctx.summary.get("non_positive_probability", 0.0))
    if non_positive > 0:
        risks.append(
            f"{percent(non_positive)} dos cenários terminam com valuation igual ou inferior "
            "a zero."
        )
    if uncertainty.label in {"HIGH", "VERY HIGH"}:
        risks.append(uncertainty.sentence)
    # The failure rate is already stated above; do not repeat it as a downside driver.
    tail = next((item for item in downside if item.name != "failure_state"), None)
    if tail is not None:
        risks.append(tail.text)
    if sensitivity:
        risks.append(sensitivity)
    if r_squared is not None and r_squared < LOW_FIT:
        risks.append(
            f"Os drivers explicam apenas {percent(r_squared, decimals=0)} da variação do "
            "valuation; interações entre premissas são relevantes."
        )
    return tuple(risks[:5])


def _executive_summary(
    ctx: _Context,
    uncertainty: UncertaintyInsight,
    drivers_sentence: str | None,
    upside: Sequence[TailInsight],
    downside: Sequence[TailInsight],
    target: TargetInsight | None,
    sensitivity_top: Mapping[str, Any] | None,
) -> tuple[str, ...]:
    p = ctx.p
    paragraphs = [
        f"Nos {_integer(ctx.count)} cenários simulados, o valuation mediano foi de "
        f"{ctx.money(p['p50'])}, com faixa central (P25–P75) entre {ctx.money(p['p25'])} e "
        f"{ctx.money(p['p75'])}. No cenário conservador (P10), o valuation foi de "
        f"{ctx.money(p['p10'])} e, no otimista (P90), de {ctx.money(p['p90'])}. "
        f"{uncertainty.sentence}"
    ]
    second: list[str] = []
    if drivers_sentence:
        second.append(drivers_sentence)
    if upside:
        second.append(
            "Os melhores cenários combinam "
            f"{_join([_phrase(describe(t.name), t.direction) for t in upside])}."
        )
    if downside:
        second.append(
            "Os piores concentram "
            f"{_join([_phrase(describe(t.name), t.direction) for t in downside])}."
        )
    if second:
        paragraphs.append(" ".join(second))
    third: list[str] = []
    if target is not None:
        third.append(target.probability_sentence)
        if target.sample_note != "empty_group":
            third.append(target.interpretation)
    risks: list[str] = []
    failure = float(ctx.summary.get("failure_probability", 0.0))
    if failure > 0:
        risks.append(f"encerramento das operações em {percent(failure)} dos cenários")
    non_positive = float(ctx.summary.get("non_positive_probability", 0.0))
    if non_positive > 0:
        risks.append(f"valuation igual ou inferior a zero em {percent(non_positive)} dos cenários")
    if sensitivity_top is not None and sensitivity_top["swing"] > 0:
        spec = describe(sensitivity_top["parameter"])
        risks.append(
            f"premissa mais sensível: {spec.label} (valuation mediano de "
            f"{ctx.money(sensitivity_top['value_at_low'])} a "
            f"{ctx.money(sensitivity_top['value_at_high'])})"
        )
    if risks:
        third.append(f"Principais riscos: {'; '.join(risks)}.")
    third.append("As associações descritas neste resumo não implicam causalidade.")
    paragraphs.append(" ".join(third))
    return tuple(paragraphs)


METHOD_NOTES = (
    "Drivers: correlação de Spearman e coeficientes de regressão padronizada sobre postos "
    "(SRRC) dos fatores primitivos; a participação é a parcela da variância explicada dos "
    "postos atribuída a cada fator (método drivers-v1).",
    "Incerteza: regra uncertainty-v1 sobre o intervalo P25–P75 relativo à mediana (baixa "
    "abaixo de 40%, moderada até 80%, alta até 150%, muito alta acima), elevada a muito alta "
    "quando a mediana não é positiva ou 25% ou mais dos cenários valem zero ou menos.",
    "Upside e downside: comparação dos 10% melhores e dos 10% piores cenários com o "
    "conjunto; só aparecem deslocamentos de pelo menos 0,25 intervalo interquartil ou 5 "
    "pontos percentuais.",
    "Meta: tamanho de efeito pelo delta de Cliff entre os cenários que atingem e os demais; "
    "o limiar é o quartil do grupo que atinge a meta.",
    "Tornado: variação de uma premissa por vez sobre os mesmos cenários simulados "
    "(método tornado-v1).",
)


def build_insight(
    *,
    summary: Mapping[str, Any],
    valuations: np.ndarray,
    factors: Mapping[str, np.ndarray],
    currency: str,
    target: float | None,
) -> InsightReport:
    ctx = _Context(summary, valuations, factors, currency)
    uncertainty = _uncertainty(ctx)
    ranking = _ranking(ctx)
    key_drivers, drivers_sentence = _key_drivers(ranking)
    order = [
        item["name"]
        for item in ranking["items"]
        if item["contribution"] is not None and item["contribution"] >= MIN_DRIVER_SHARE
    ]
    drivers, _ = split_by_role(factors)
    upside_shifts, downside_shifts = tail_shifts(drivers, ctx.values, order=order)
    upside = tuple(_tail_text(ctx, shift) for shift in upside_shifts)
    downside = tuple(_tail_text(ctx, shift) for shift in downside_shifts)
    sensitivity = _sensitivity(ctx)
    stored_tornado = summary.get("sensitivity")
    top_tornado = (
        stored_tornado["items"][0]
        if isinstance(stored_tornado, Mapping) and stored_tornado.get("items")
        else None
    )
    target_insight = _target(ctx, target) if target is not None else None
    p = ctx.p
    return InsightReport(
        INSIGHT_TEMPLATE_VERSION,
        f"Valuation mediano de {ctx.money(p['p50'])}, com faixa central entre "
        f"{ctx.money(p['p25'])} e {ctx.money(p['p75'])}",
        _valuation_paragraphs(ctx),
        uncertainty,
        drivers_sentence,
        key_drivers,
        upside,
        downside,
        sensitivity,
        _risks(ctx, uncertainty, downside, sensitivity, ranking.get("r_squared")),
        target_insight,
        _executive_summary(
            ctx, uncertainty, drivers_sentence, upside, downside, target_insight, top_tornado
        ),
        METHOD_NOTES,
    )
